#!/usr/bin/env python3
"""Generate a compiler-friendly, byte-exact C++ embedding for tokenizer.json."""
from __future__ import annotations
import argparse
from pathlib import Path


def encode_byte(b: int) -> str:
    # Preserve safe printable ASCII; escape everything whose spelling could be
    # reinterpreted by the C++ lexer/source charset. Fixed-width octal escapes
    # are byte-exact and do not consume following decimal/hex characters.
    if 0x20 <= b <= 0x7E and b not in (0x22, 0x5C):
        return chr(b)
    if b == 0x22:
        return r'\"'
    if b == 0x5C:
        return r'\\'
    return f"\\{b:03o}"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("input", type=Path)
    ap.add_argument("source", type=Path)
    ap.add_argument("header", type=Path)
    args = ap.parse_args()
    data = args.input.read_bytes()

    args.header.write_text(
        "#pragma once\n#include <cstddef>\n"
        "extern const char tokenizer_json_data[];\n"
        "extern const std::size_t tokenizer_json_size;\n",
        encoding="ascii", newline="\n")

    # Keep each physical source line modest. Adjacent string literals are
    # concatenated by the compiler without a giant initializer expression.
    target = 8192
    lines: list[str] = []
    cur: list[str] = []
    n = 0
    for b in data:
        e = encode_byte(b)
        if n + len(e) > target and cur:
            lines.append('"' + ''.join(cur) + '"')
            cur, n = [], 0
        cur.append(e); n += len(e)
    if cur:
        lines.append('"' + ''.join(cur) + '"')

    with args.source.open("w", encoding="ascii", newline="\n") as f:
        f.write('// Generated by tools/embed_tokenizer.py. DO NOT EDIT.\n')
        f.write('#include "tokenizer_data.h"\n\n')
        f.write(f'const std::size_t tokenizer_json_size = {len(data)}ULL;\n')
        f.write('const char tokenizer_json_data[] =\n')
        for line in lines:
            f.write(line + '\n')
        f.write(';\n')
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
