// ============================================================================
//  crash_demo.cpp  —  reproduces the ORIGINAL (pre-fix) parser crash.
//  Self-contained; bundles the UNPATCHED parse_args (no try/catch). Build & run:
//
//      g++ -std=c++17 -o crash_demo crash_demo.cpp && ./crash_demo ; echo "exit=$?"
//
//  Expected: prints "terminate called after throwing an instance of
//  'std::invalid_argument'", then "Aborted", exit code 134 (SIGABRT). On the
//  PATCHED build (main.cpp / test_cli_parser.cpp) the same "-v abc" instead
//  prints "Invalid value for option '-v': stoi" and returns exit code 1.
// ============================================================================
// AUTO-GENERATED by gen_parser.py from src/main.cpp — DO NOT EDIT BY HAND.
// The parse_args() body below is extracted verbatim from main.cpp's argument
// loop, so it always reflects the shipped parser. Regenerate after editing
// main.cpp's parser:  python3 gen_parser.py src/main.cpp parser_extracted.inc
#include <cstdint>
#include <cstddef>
#include <string>
#include <iostream>
#include <stdexcept>

// Stub structs mirroring the real PipelineParams / GenerateParams
// (include/s2_pipeline.h, include/s2_generate.h) — field names, types and
// defaults must match exactly or this file will not compile.
struct GenerateParams {
    int32_t max_new_tokens          = 512;
    float   temperature             = 0.7f;
    float   top_p                   = 0.7f;
    int32_t top_k                   = 30;
    int32_t min_tokens_before_end   = 64;
    int32_t n_threads               = 4;
    bool    verbose                 = true;
    int32_t ras_window_size         = 10;
    float   ras_high_temp           = 1.0f;
    float   ras_high_top_p          = 0.9f;
};

struct PipelineParams {
    std::string model_path;
    std::string tokenizer_path;
    std::string codec_model_path;
    std::string base_dir;
    const char * tokenizer_data      = nullptr;
    size_t       tokenizer_data_size = 0;
    std::string text;
    std::string prompt_text;
    std::string prompt_audio_path;
    std::string output_path;
    GenerateParams gen;
    int32_t vulkan_device       = -1;
    int32_t codec_vulkan_device = -1;
    bool    segment_sentences      = false;
    int32_t codec_chunk_frames     = 0;
    int32_t codec_overlap_frames   = 0;
    int32_t max_tokens_per_segment = 300;
    int32_t min_seg_chars          = 0;
    bool trim_silence = false;
    std::string voice_id;
    bool        save_voice        = false;
    std::string voice_storage_dir = "./voices";
    int32_t stream_decode_stride_frames = 0;
};

// Returns 0 = parsed OK, 1 = error/exit, 2 = --help.
int parse_args(int argc, char** argv,
               PipelineParams& params, int& port, bool& list_voices) {
    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];
        if ((arg == "-m" || arg == "--model") && i + 1 < argc) {
            params.model_path = argv[++i];
        } else if (arg == "--model-codec" && i + 1 < argc) {
            params.codec_model_path = argv[++i];
        } else if ((arg == "-t" || arg == "--tokenizer") && i + 1 < argc) {
            params.tokenizer_path = argv[++i];
        } else if ((arg == "-v" || arg == "--vulkan") && i + 1 < argc) {
            params.vulkan_device = std::stoi(argv[++i]);
        } else if (arg == "--codec-vulkan" && i + 1 < argc) {
            params.codec_vulkan_device = std::stoi(argv[++i]);
        } else if (arg == "--segment") {
            params.segment_sentences = true;
        } else if (arg == "--codec-chunk" && i + 1 < argc) {
            params.codec_chunk_frames = std::stoi(argv[++i]);
        } else if (arg == "--codec-overlap" && i + 1 < argc) {
            params.codec_overlap_frames = std::stoi(argv[++i]);
        } else if (arg == "--min-seg-chars" && i + 1 < argc) {
            params.min_seg_chars = std::stoi(argv[++i]);
        } else if ((arg == "--temperature" || arg == "--temp") && i + 1 < argc) {
            params.gen.temperature = std::stof(argv[++i]);
        } else if (arg == "--top-p" && i + 1 < argc) {
            params.gen.top_p = std::stof(argv[++i]);
        } else if (arg == "--top-k" && i + 1 < argc) {
            params.gen.top_k = std::stoi(argv[++i]);
        } else if (arg == "--min-end-tokens" && i + 1 < argc) {
            params.gen.min_tokens_before_end = std::stoi(argv[++i]);
        } else if (arg == "--ras-window" && i + 1 < argc) {
            params.gen.ras_window_size = std::stoi(argv[++i]);
        } else if (arg == "--ras-temp" && i + 1 < argc) {
            params.gen.ras_high_temp = std::stof(argv[++i]);
        } else if (arg == "--ras-top-p" && i + 1 < argc) {
            params.gen.ras_high_top_p = std::stof(argv[++i]);
        } else if (arg == "--max-seg-tokens" && i + 1 < argc) {
            params.max_tokens_per_segment = std::stoi(argv[++i]);
        } else if ((arg == "-p" || arg == "--port") && i + 1 < argc) {
            port = std::stoi(argv[++i]);
        } else if ((arg == "-threads" || arg == "--threads") && i + 1 < argc) {
            params.gen.n_threads = std::stoi(argv[++i]);
        } else if ((arg == "--max-tokens") && i + 1 < argc) {
            params.gen.max_new_tokens = std::stoi(argv[++i]);
        } else if ((arg == "--text") && i + 1 < argc) {
            params.text = argv[++i];
        } else if ((arg == "-pa" || arg == "--prompt-audio") && i + 1 < argc) {
            params.prompt_audio_path = argv[++i];
        } else if ((arg == "-pt" || arg == "--prompt-text") && i + 1 < argc) {
            params.prompt_text = argv[++i];
        } else if (arg == "--voice" && i + 1 < argc) {
            params.voice_id = argv[++i];
        } else if (arg == "--save-voice") {
            params.save_voice = true;
        } else if (arg == "--voice-dir" && i + 1 < argc) {
            params.voice_storage_dir = argv[++i];
        } else if (arg == "--list-voices") {
            list_voices = true;
        } else if ((arg == "-o" || arg == "--output") && i + 1 < argc) {
            params.output_path = argv[++i];
        } else if (arg == "--trim-silence") {
            params.trim_silence = true;
        } else if (arg == "--no-trim-silence") {
            params.trim_silence = false;
        } else if (arg == "--stream-decode-stride" && i + 1 < argc) {
            params.stream_decode_stride_frames = std::stoi(argv[++i]);
        } else if (arg == "--help" || arg == "-h") {
            return 2; /* help sentinel (usage text elided for tests) */
        } else {
            std::cerr << "Unknown option: " << arg << std::endl;
            std::cerr << "Use --help for usage information." << std::endl;
            return 1;
        }
    }
    return 0;
}
// Demonstrates the ORIGINAL bug: the unpatched parser (no try/catch around the
// loop) calls std::stoi on non-numeric input, which throws std::invalid_argument.
// With nothing catching it, the exception propagates out of main() and the C++
// runtime calls std::terminate() -> abort(): the process dies with SIGABRT
// (exit code 134 on Linux; 0xC0000409/0xC000001D-class abnormal exit on Windows)
// BEFORE any usage message can be printed.
//
// Build:  g++ -std=c++17 -o crash_demo crash_demo_unfixed.cpp
// Run:    ./crash_demo ; echo "exit=$?"   ->  prints "terminate called ..." then exit=134

int main() {
    PipelineParams params;
    int  port = 8080;
    bool list_voices = false;

    const char* argv[] = { "s2", "-v", "abc" };   // bad value for an int flag
    int argc = 3;

    std::cout << "calling unpatched parse_args with: -v abc\n";
    std::cout.flush();

    // NOTE: intentionally NO try/catch here — this is what main.cpp looked like
    // before the fix. std::stoi("abc") throws and the program aborts on the line
    // below; execution never reaches the return.
    int rc = parse_args(argc, const_cast<char**>(argv), params, port, list_voices);

    std::cout << "parse_args returned " << rc << " (NOT REACHED on unpatched build)\n";
    return rc;
}
