// ============================================================================
//  test_cli_parser.cpp  —  self-contained, standalone test for the s2.cpp CLI
//  argument parser. No external headers from the project, no Python, no build
//  system required. Drop it next to the repo and compile directly:
//
//      cl.exe /EHsc /std:c++17 test_cli_parser.cpp        (MSVC / Windows CI)
//      g++ -std=c++17 -Wall -Wextra -o test_cli_parser test_cli_parser.cpp
//
//  Exit code 0 = all tests passed, 1 = at least one failed (CI-friendly).
//
//  WHAT THIS TESTS
//  ---------------
//  The parse_args() body below is a SNAPSHOT of the argument-parsing loop in
//  src/main.cpp, extracted verbatim (the only edit is replacing the inline
//  --help usage text with `return 2;` as a sentinel). It therefore reflects the
//  exact branching/stoi/stof logic that ships in the binary. The stub structs
//  mirror PipelineParams / GenerateParams (include/s2_pipeline.h,
//  include/s2_generate.h) field-for-field so the snapshot compiles unchanged.
//
//  KEEPING IT IN SYNC
//  ------------------
//  This snapshot can drift if main.cpp's parser changes. To regenerate it from
//  the live source (recommended after editing the parser):
//
//      python3 gen_parser.py src/main.cpp parser_extracted.inc
//      cat parser_extracted.inc harness_body.inc > test_cli_parser.cpp
//
//  gen_parser.py re-extracts the loop by brace-matching (skipping the help
//  raw-string literal), so a renamed field or changed default will fail to
//  compile here — surfacing drift instead of silently passing.
//
//  REGRESSION COVERED
//  ------------------
//  The parser previously called std::stoi/std::stof with no surrounding
//  try/catch, so any non-numeric or out-of-range value (e.g. "-v abc",
//  "--port 9e99", "--port --segment") threw an uncaught exception ->
//  std::terminate() -> abort (SIGABRT / abnormal process exit) before any
//  usage message. The fix wraps the loop body in try/catch (requires
//  #include <stdexcept>) so such input now prints a clear message and returns
//  exit code 1. Group "invalid numeric values" below is the direct proof.
// ============================================================================

// AUTO-GENERATED by gen_parser.py from src/main.cpp — DO NOT EDIT BY HAND.
// The parse_args() body below is extracted verbatim from main.cpp's argument
// loop, so it always reflects the shipped parser. Regenerate after editing
// main.cpp's parser:  python3 gen_parser.py src/main.cpp parser_extracted.inc
#include <cstdint>
#include <cstddef>
#include <string>
#include <iostream>
#include <stdexcept>

// Stub structs mirroring the real PipelineParams / GenerateParams
// (include/s2_pipeline.h, include/s2_generate.h) — field names, types and
// defaults must match exactly or this file will not compile.
struct GenerateParams {
    int32_t max_new_tokens          = 512;
    float   temperature             = 0.7f;
    float   top_p                   = 0.7f;
    int32_t top_k                   = 30;
    int32_t min_tokens_before_end   = 64;
    int32_t n_threads               = 4;
    bool    verbose                 = true;
    int32_t ras_window_size         = 10;
    float   ras_high_temp           = 1.0f;
    float   ras_high_top_p          = 0.9f;
};

struct PipelineParams {
    std::string model_path;
    std::string tokenizer_path;
    std::string codec_model_path;
    std::string base_dir;
    const char * tokenizer_data      = nullptr;
    size_t       tokenizer_data_size = 0;
    std::string text;
    std::string prompt_text;
    std::string prompt_audio_path;
    std::string output_path;
    GenerateParams gen;
    int32_t vulkan_device       = -1;
    int32_t codec_vulkan_device = -2;
    bool    segment_sentences      = false;
    int32_t codec_chunk_frames     = 0;
    int32_t codec_overlap_frames   = 0;
    int32_t max_tokens_per_segment = 300;
    int32_t min_seg_chars          = 0;
    bool trim_silence = false;
    std::string voice_id;
    bool        save_voice        = false;
    std::string voice_storage_dir = "./voices";
    int32_t stream_decode_stride_frames = 0;
};

static int parse_int_arg(const char * raw) {
    if (!raw) throw std::invalid_argument("missing numeric value");
    const std::string value(raw);
    size_t pos = 0;
    const int parsed = std::stoi(value, &pos, 10);
    if (pos != value.size()) throw std::invalid_argument("trailing characters in integer: " + value);
    return parsed;
}

static float parse_float_arg(const char * raw) {
    if (!raw) throw std::invalid_argument("missing numeric value");
    const std::string value(raw);
    size_t pos = 0;
    const float parsed = std::stof(value, &pos);
    if (pos != value.size()) throw std::invalid_argument("trailing characters in number: " + value);
    return parsed;
}

// Returns 0 = parsed OK, 1 = error/exit, 2 = --help.
int parse_args(int argc, char** argv,
               PipelineParams& params, int& port, std::string& bind_host, bool& list_voices) {
    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];
        // std::stoi / std::stof throw std::invalid_argument on non-numeric input
        // and std::out_of_range on oversized values. Guard every iteration so a
        // bad value (e.g. "-v abc", "--port 9e99", or "--port --segment") yields a
        // clean error + exit code 1 instead of an uncaught exception -> std::terminate()
        // -> process abort. (Critical Pattern #2 — was missing from the parse loop.)
        try {
        if ((arg == "-m" || arg == "--model") && i + 1 < argc) {
            params.model_path = argv[++i];
        } else if (arg == "--model-codec" && i + 1 < argc) {
            params.codec_model_path = argv[++i];
        } else if ((arg == "-t" || arg == "--tokenizer") && i + 1 < argc) {
            params.tokenizer_path = argv[++i];
        } else if ((arg == "-v" || arg == "--vulkan") && i + 1 < argc) {
            params.vulkan_device = parse_int_arg(argv[++i]);
        } else if (arg == "--codec-vulkan" && i + 1 < argc) {
            params.codec_vulkan_device = parse_int_arg(argv[++i]);
        } else if (arg == "--segment") {
            params.segment_sentences = true;
        } else if (arg == "--codec-chunk" && i + 1 < argc) {
            params.codec_chunk_frames = parse_int_arg(argv[++i]);
        } else if (arg == "--codec-overlap" && i + 1 < argc) {
            params.codec_overlap_frames = parse_int_arg(argv[++i]);
        } else if (arg == "--min-seg-chars" && i + 1 < argc) {
            params.min_seg_chars = parse_int_arg(argv[++i]);
        } else if ((arg == "--temperature" || arg == "--temp") && i + 1 < argc) {
            params.gen.temperature = parse_float_arg(argv[++i]);
        } else if (arg == "--top-p" && i + 1 < argc) {
            params.gen.top_p = parse_float_arg(argv[++i]);
        } else if (arg == "--top-k" && i + 1 < argc) {
            params.gen.top_k = parse_int_arg(argv[++i]);
        } else if (arg == "--min-end-tokens" && i + 1 < argc) {
            params.gen.min_tokens_before_end = parse_int_arg(argv[++i]);
        } else if (arg == "--ras-window" && i + 1 < argc) {
            params.gen.ras_window_size = parse_int_arg(argv[++i]);
        } else if (arg == "--ras-temp" && i + 1 < argc) {
            params.gen.ras_high_temp = parse_float_arg(argv[++i]);
        } else if (arg == "--ras-top-p" && i + 1 < argc) {
            params.gen.ras_high_top_p = parse_float_arg(argv[++i]);
        } else if (arg == "--max-seg-tokens" && i + 1 < argc) {
            params.max_tokens_per_segment = parse_int_arg(argv[++i]);
        } else if ((arg == "-p" || arg == "--port") && i + 1 < argc) {
            port = parse_int_arg(argv[++i]);
        } else if (arg == "--host" && i + 1 < argc) {
            bind_host = argv[++i];
        } else if ((arg == "-threads" || arg == "--threads") && i + 1 < argc) {
            params.gen.n_threads = parse_int_arg(argv[++i]);
        } else if ((arg == "--max-tokens") && i + 1 < argc) {
            params.gen.max_new_tokens = parse_int_arg(argv[++i]);
        } else if ((arg == "--text") && i + 1 < argc) {
            params.text = argv[++i];
        } else if ((arg == "-pa" || arg == "--prompt-audio") && i + 1 < argc) {
            params.prompt_audio_path = argv[++i];
        } else if ((arg == "-pt" || arg == "--prompt-text") && i + 1 < argc) {
            params.prompt_text = argv[++i];
        } else if (arg == "--voice" && i + 1 < argc) {
            params.voice_id = argv[++i];
        } else if (arg == "--save-voice") {
            params.save_voice = true;
        } else if (arg == "--voice-dir" && i + 1 < argc) {
            params.voice_storage_dir = argv[++i];
        } else if (arg == "--list-voices") {
            list_voices = true;
        } else if ((arg == "-o" || arg == "--output") && i + 1 < argc) {
            params.output_path = argv[++i];
        } else if (arg == "--trim-silence") {
            params.trim_silence = true;
        } else if (arg == "--no-trim-silence") {
            params.trim_silence = false;
        } else if (arg == "--stream-decode-stride" && i + 1 < argc) {
            params.stream_decode_stride_frames = parse_int_arg(argv[++i]);
        } else if (arg == "--help" || arg == "-h") {
            return 2; /* help sentinel (usage text elided for tests) */
        } else {
            std::cerr << "Unknown option: " << arg << std::endl;
            std::cerr << "Use --help for usage information." << std::endl;
            return 1;
        }
        } catch (const std::exception & e) {
            std::cerr << "Invalid value for option '" << arg << "': " << e.what() << std::endl;
            std::cerr << "Use --help for usage information." << std::endl;
            return 1;
        }
    }
    return 0;
}
// ============================================================================
//  Test harness body — exhaustively exercises every command-line argument of
//  the s2.cpp parser. Included after a parser .inc that defines parse_args(),
//  PipelineParams and GenerateParams.
//
//  Strategy: parse_args() is the VERBATIM argument loop extracted from
//  src/main.cpp (see header of the parser .inc), so passing here proves the
//  shipped parser is correct, not a hand-written replica.
//
//  parse_args() return contract:  0 = parsed OK, 1 = error/exit, 2 = --help.
// ============================================================================
#include <sstream>
#include <vector>
#include <string>
#include <iostream>

static int g_pass = 0;
static int g_fail = 0;

struct RunResult {
    int          rc = 0;
    PipelineParams params;
    int          port = 8080;
    std::string  bind_host = "127.0.0.1";
    bool         list_voices = false;
    std::string  err;                  // captured std::cerr
};

// Build argv from args (argv[0] synthesised) and run the real parser,
// capturing everything written to std::cerr.
static RunResult run(const std::vector<std::string>& args) {
    std::vector<std::string> store;
    store.reserve(args.size() + 1);
    store.push_back("s2");
    for (const auto& a : args) store.push_back(a);

    std::vector<char*> argv;
    argv.reserve(store.size());
    for (auto& s : store) argv.push_back(&s[0]);

    RunResult r;
    std::ostringstream capture;
    std::streambuf* old = std::cerr.rdbuf(capture.rdbuf());
    r.rc = parse_args((int)argv.size(), argv.data(), r.params, r.port, r.bind_host, r.list_voices);
    std::cerr.rdbuf(old);
    r.err = capture.str();
    return r;
}

static void ok(bool cond, const std::string& name) {
    if (cond) { ++g_pass; }
    else      { ++g_fail; std::cout << "  [FAIL] " << name << "\n"; }
}

// Convenience: assert the parser returned a given rc for a given argv.
static void expect_rc(const std::vector<std::string>& args, int want,
                      const std::string& name) {
    RunResult r = run(args);
    if (r.rc == want) { ++g_pass; }
    else {
        ++g_fail;
        std::cout << "  [FAIL] " << name << "  (rc=" << r.rc
                  << " want " << want << ")";
        if (!r.err.empty()) {
            std::string e = r.err;
            if (!e.empty() && e.back() == '\n') e.pop_back();
            std::cout << "  cerr=\"" << e << "\"";
        }
        std::cout << "\n";
    }
}

static bool feq(float a, float b) { return (a > b ? a - b : b - a) < 1e-6f; }

int main() {
    std::cout << "=== s2.cpp CLI argument parser test harness ===\n\n";

    // ----------------------------------------------------------------------
    // 1. Every value-consuming flag with a VALID value (long form + aliases).
    //    Verify rc==0 AND the value landed in the right field.
    // ----------------------------------------------------------------------
    std::cout << "[group] valid value-consuming flags\n";
    { RunResult r = run({"-m","model.gguf"});            ok(r.rc==0 && r.params.model_path=="model.gguf", "-m sets model_path"); }
    { RunResult r = run({"--model","m.gguf"});           ok(r.rc==0 && r.params.model_path=="m.gguf", "--model sets model_path"); }
    { RunResult r = run({"--model-codec","c.gguf"});     ok(r.rc==0 && r.params.codec_model_path=="c.gguf", "--model-codec sets codec_model_path"); }
    { RunResult r = run({"-t","tok.json"});              ok(r.rc==0 && r.params.tokenizer_path=="tok.json", "-t sets tokenizer_path"); }
    { RunResult r = run({"--tokenizer","tok.json"});     ok(r.rc==0 && r.params.tokenizer_path=="tok.json", "--tokenizer sets tokenizer_path"); }
    { RunResult r = run({"-v","1"});                     ok(r.rc==0 && r.params.vulkan_device==1, "-v sets vulkan_device"); }
    { RunResult r = run({"--vulkan","2"});               ok(r.rc==0 && r.params.vulkan_device==2, "--vulkan sets vulkan_device"); }
    { RunResult r = run({"--codec-vulkan","1"});         ok(r.rc==0 && r.params.codec_vulkan_device==1, "--codec-vulkan sets codec_vulkan_device"); }
    { RunResult r = run({"--codec-chunk","32"});         ok(r.rc==0 && r.params.codec_chunk_frames==32, "--codec-chunk sets codec_chunk_frames"); }
    { RunResult r = run({"--codec-overlap","4"});        ok(r.rc==0 && r.params.codec_overlap_frames==4, "--codec-overlap sets codec_overlap_frames"); }
    { RunResult r = run({"--min-seg-chars","60"});       ok(r.rc==0 && r.params.min_seg_chars==60, "--min-seg-chars sets min_seg_chars"); }
    { RunResult r = run({"--temperature","0.8"});        ok(r.rc==0 && feq(r.params.gen.temperature,0.8f), "--temperature sets gen.temperature"); }
    { RunResult r = run({"--temp","0.5"});               ok(r.rc==0 && feq(r.params.gen.temperature,0.5f), "--temp alias sets gen.temperature"); }
    { RunResult r = run({"--top-p","0.8"});              ok(r.rc==0 && feq(r.params.gen.top_p,0.8f), "--top-p sets gen.top_p"); }
    { RunResult r = run({"--top-k","40"});               ok(r.rc==0 && r.params.gen.top_k==40, "--top-k sets gen.top_k"); }
    { RunResult r = run({"--min-end-tokens","64"});      ok(r.rc==0 && r.params.gen.min_tokens_before_end==64, "--min-end-tokens sets gen.min_tokens_before_end"); }
    { RunResult r = run({"--ras-window","10"});          ok(r.rc==0 && r.params.gen.ras_window_size==10, "--ras-window sets gen.ras_window_size"); }
    { RunResult r = run({"--ras-temp","1.2"});           ok(r.rc==0 && feq(r.params.gen.ras_high_temp,1.2f), "--ras-temp sets gen.ras_high_temp"); }
    { RunResult r = run({"--ras-top-p","0.9"});          ok(r.rc==0 && feq(r.params.gen.ras_high_top_p,0.9f), "--ras-top-p sets gen.ras_high_top_p"); }
    { RunResult r = run({"--max-seg-tokens","300"});     ok(r.rc==0 && r.params.max_tokens_per_segment==300, "--max-seg-tokens sets max_tokens_per_segment"); }
    { RunResult r = run({"-p","9090"});                  ok(r.rc==0 && r.port==9090, "-p sets port"); }
    { RunResult r = run({"--port","8000"});              ok(r.rc==0 && r.port==8000, "--port sets port"); }
    { RunResult r = run({"--host","0.0.0.0"});            ok(r.rc==0 && r.bind_host=="0.0.0.0", "--host sets bind_host"); }
    { RunResult r = run({"--threads","8"});              ok(r.rc==0 && r.params.gen.n_threads==8, "--threads sets gen.n_threads"); }
    { RunResult r = run({"-threads","6"});               ok(r.rc==0 && r.params.gen.n_threads==6, "-threads (single-dash alias) sets gen.n_threads"); }
    { RunResult r = run({"--max-tokens","512"});         ok(r.rc==0 && r.params.gen.max_new_tokens==512, "--max-tokens sets gen.max_new_tokens"); }
    { RunResult r = run({"--text","hello world"});       ok(r.rc==0 && r.params.text=="hello world", "--text sets text"); }
    { RunResult r = run({"-pa","ref.wav"});              ok(r.rc==0 && r.params.prompt_audio_path=="ref.wav", "-pa sets prompt_audio_path"); }
    { RunResult r = run({"--prompt-audio","ref.wav"});   ok(r.rc==0 && r.params.prompt_audio_path=="ref.wav", "--prompt-audio sets prompt_audio_path"); }
    { RunResult r = run({"-pt","reference text"});       ok(r.rc==0 && r.params.prompt_text=="reference text", "-pt sets prompt_text"); }
    { RunResult r = run({"--prompt-text","reference"});  ok(r.rc==0 && r.params.prompt_text=="reference", "--prompt-text sets prompt_text"); }
    { RunResult r = run({"--voice","alice"});            ok(r.rc==0 && r.params.voice_id=="alice", "--voice sets voice_id"); }
    { RunResult r = run({"--voice-dir","/voices"});      ok(r.rc==0 && r.params.voice_storage_dir=="/voices", "--voice-dir sets voice_storage_dir"); }
    { RunResult r = run({"-o","out.wav"});               ok(r.rc==0 && r.params.output_path=="out.wav", "-o sets output_path"); }
    { RunResult r = run({"--output","out.wav"});         ok(r.rc==0 && r.params.output_path=="out.wav", "--output sets output_path"); }
    { RunResult r = run({"--stream-decode-stride","16"});ok(r.rc==0 && r.params.stream_decode_stride_frames==16, "--stream-decode-stride sets stream_decode_stride_frames"); }

    // ----------------------------------------------------------------------
    // 2. Boolean flags.
    // ----------------------------------------------------------------------
    std::cout << "[group] boolean flags\n";
    { RunResult r = run({"--segment"});                  ok(r.rc==0 && r.params.segment_sentences==true, "--segment sets segment_sentences"); }
    { RunResult r = run({"--save-voice"});               ok(r.rc==0 && r.params.save_voice==true, "--save-voice sets save_voice"); }
    { RunResult r = run({"--list-voices"});              ok(r.rc==0 && r.list_voices==true, "--list-voices sets list_voices"); }
    { RunResult r = run({"--trim-silence"});             ok(r.rc==0 && r.params.trim_silence==true, "--trim-silence sets trim_silence=true"); }
    { RunResult r = run({"--trim-silence","--no-trim-silence"}); ok(r.rc==0 && r.params.trim_silence==false, "--no-trim-silence overrides --trim-silence"); }
    expect_rc({"-h"}, 2, "-h returns help sentinel (2)");
    expect_rc({"--help"}, 2, "--help returns help sentinel (2)");

    // ----------------------------------------------------------------------
    // 3. THE CORE FIX: invalid numeric value on EVERY numeric flag must yield
    //    a clean rc==1 (not an uncaught exception -> std::terminate -> abort).
    // ----------------------------------------------------------------------
    std::cout << "[group] invalid numeric values -> clean exit 1 (core fix)\n";
    const char* int_flags[] = {
        "-v","--vulkan","--codec-vulkan","--codec-chunk","--codec-overlap",
        "--min-seg-chars","--top-k","--min-end-tokens","--ras-window",
        "--max-seg-tokens","-p","--port","--threads","-threads","--max-tokens",
        "--stream-decode-stride"
    };
    for (const char* f : int_flags)
        expect_rc({f, "abc"}, 1, std::string("int flag ") + f + " rejects non-numeric");

    const char* float_flags[] = {
        "--temperature","--temp","--top-p","--ras-temp","--ras-top-p"
    };
    for (const char* f : float_flags)
        expect_rc({f, "xyz"}, 1, std::string("float flag ") + f + " rejects non-numeric");

    // ----------------------------------------------------------------------
    // 4. Out-of-range numbers -> std::out_of_range -> clean rc==1.
    // ----------------------------------------------------------------------
    std::cout << "[group] out-of-range numbers -> clean exit 1\n";
    expect_rc({"--port","99999999999999999999"}, 1, "--port out-of-range rejected");
    expect_rc({"--max-tokens","99999999999999999999"}, 1, "--max-tokens out-of-range rejected");

    // ----------------------------------------------------------------------
    // 5. Value flag whose "value" is actually the next flag (non-numeric) ->
    //    stoi throws -> clean rc==1. (Pre-fix: abort.)
    // ----------------------------------------------------------------------
    std::cout << "[group] next-arg-is-a-flag swallowed as value\n";
    expect_rc({"--port","--segment"}, 1, "--port --segment: stoi(--segment) rejected");
    expect_rc({"-v","--help"}, 1, "-v --help: --help swallowed as -v value, rc=1 (not help)");

    // ----------------------------------------------------------------------
    // 6. Dangling value flag as the LAST arg (no value). i+1<argc is false, so
    //    the branch is skipped and it falls through to Unknown option -> rc==1.
    //    (Documented wart: message says "Unknown option", but it is not a crash.)
    // ----------------------------------------------------------------------
    std::cout << "[group] dangling last-arg value flag\n";
    expect_rc({"-v"}, 1, "trailing -v with no value -> rc 1 (no crash)");
    expect_rc({"--port"}, 1, "trailing --port with no value -> rc 1 (no crash)");
    expect_rc({"--model"}, 1, "trailing --model with no value -> rc 1 (no crash)");
    expect_rc({"--host"}, 1, "trailing --host with no value -> rc 1 (no crash)");

    // ----------------------------------------------------------------------
    // 7. Unknown options and empty string.
    // ----------------------------------------------------------------------
    std::cout << "[group] unknown options / empty string\n";
    expect_rc({"--bogus"}, 1, "--bogus unknown option -> rc 1");
    expect_rc({"-xyz"}, 1, "-xyz unknown option -> rc 1");
    expect_rc({""}, 1, "empty-string arg -> rc 1");

    // ----------------------------------------------------------------------
    // 8. Negative device indices are valid (-2=inherit, -1=CPU).
    // ----------------------------------------------------------------------
    std::cout << "[group] negative numeric values are valid\n";
    { RunResult r = run({"-v","-1"});                    ok(r.rc==0 && r.params.vulkan_device==-1, "-v -1 -> vulkan_device=-1 (CPU)"); }
    { RunResult r = run({"--codec-vulkan","-2"});        ok(r.rc==0 && r.params.codec_vulkan_device==-2, "--codec-vulkan -2 -> -2 (inherit)"); }
    { RunResult r = run({"--codec-vulkan","-1"});        ok(r.rc==0 && r.params.codec_vulkan_device==-1, "--codec-vulkan -1 -> -1 (CPU)"); }

    // ----------------------------------------------------------------------
    // 9. Trailing garbage must be rejected instead of silently truncating.
    // ----------------------------------------------------------------------
    std::cout << "[group] trailing garbage rejected\n";
    expect_rc({"--max-tokens","12abc"}, 1, "--max-tokens 12abc rejected");
    expect_rc({"-v","3x"}, 1, "-v 3x rejected");
    expect_rc({"--temperature","0.7oops"}, 1, "--temperature trailing garbage rejected");

    // ----------------------------------------------------------------------
    // 10. Duplicate flags: last occurrence wins.
    // ----------------------------------------------------------------------
    std::cout << "[group] duplicate flags (last wins)\n";
    { RunResult r = run({"-v","0","-v","1"});            ok(r.rc==0 && r.params.vulkan_device==1, "-v 0 -v 1 -> 1 (last wins)"); }
    { RunResult r = run({"--port","8000","--port","9000"}); ok(r.rc==0 && r.port==9000, "--port 8000 --port 9000 -> 9000 (last wins)"); }

    // ----------------------------------------------------------------------
    // 11. Ordering / short-circuit semantics.
    // ----------------------------------------------------------------------
    std::cout << "[group] ordering and short-circuit\n";
    expect_rc({"--help","--bogus"}, 2, "--help before junk -> 2 (returns before junk)");
    expect_rc({"-v","abc","--help"}, 1, "-v abc before --help -> 1 (throws before help)");
    expect_rc({"-m","model.gguf","--help"}, 2, "valid flag then --help -> 2");

    // ----------------------------------------------------------------------
    // 12. Large, fully-valid combined command line (the capsule's optimal CMD).
    // ----------------------------------------------------------------------
    std::cout << "[group] full valid command line\n";
    {
        RunResult r = run({
            "--model","s2-pro-q4_k_m-transformer-only.gguf",
            "--model-codec","s2-pro-q4_k_m-codec-only.gguf",
            "-v","1","--codec-vulkan","1","--segment","--codec-chunk","32",
            "--max-seg-tokens","300","--min-seg-chars","60",
            "--temperature","0.8","--top-p","0.8","--top-k","40","--port","8080",
            "--host","127.0.0.1"
        });
        ok(r.rc==0
           && r.params.model_path=="s2-pro-q4_k_m-transformer-only.gguf"
           && r.params.codec_model_path=="s2-pro-q4_k_m-codec-only.gguf"
           && r.params.vulkan_device==1
           && r.params.codec_vulkan_device==1
           && r.params.segment_sentences==true
           && r.params.codec_chunk_frames==32
           && r.params.max_tokens_per_segment==300
           && r.params.min_seg_chars==60
           && feq(r.params.gen.temperature,0.8f)
           && feq(r.params.gen.top_p,0.8f)
           && r.params.gen.top_k==40
           && r.port==8080
           && r.bind_host=="127.0.0.1",
           "full optimal Vulkan command line parses with all fields correct");
    }
    // A full voice-cloning CLI line exercising -pa/-pt/-o together.
    {
        RunResult r = run({
            "-m","m.gguf","--model-codec","c.gguf",
            "-pa","ref.wav","-pt","this is the reference transcript",
            "--voice","narrator","--save-voice","--voice-dir","./voices",
            "-o","out.wav","--trim-silence","-v","0"
        });
        ok(r.rc==0
           && r.params.prompt_audio_path=="ref.wav"
           && r.params.prompt_text=="this is the reference transcript"
           && r.params.voice_id=="narrator"
           && r.params.save_voice==true
           && r.params.voice_storage_dir=="./voices"
           && r.params.output_path=="out.wav"
           && r.params.trim_silence==true
           && r.params.vulkan_device==0,
           "full voice-cloning command line parses with all fields correct");
    }

    // ----------------------------------------------------------------------
    // 13. No args at all -> rc 0, everything at defaults.
    // ----------------------------------------------------------------------
    std::cout << "[group] no arguments\n";
    {
        RunResult r = run({});
        ok(r.rc==0 && r.port==8080 && r.bind_host=="127.0.0.1" && r.list_voices==false
           && r.params.vulkan_device==-1 && r.params.codec_vulkan_device==-2
           && r.params.segment_sentences==false && r.params.max_tokens_per_segment==300,
           "no args -> rc 0 with defaults intact");
    }

    // ----------------------------------------------------------------------
    std::cout << "\n=== RESULTS ===\n";
    std::cout << "passed: " << g_pass << "\n";
    std::cout << "failed: " << g_fail << "\n";
    if (g_fail == 0) std::cout << "ALL TESTS PASSED\n";
    else             std::cout << "SOME TESTS FAILED\n";
    return g_fail == 0 ? 0 : 1;
}
